# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('ranking', '0001_initial'), ('ranking', '0002_auto_20170611_0134'), ('ranking', '0003_auto_20170611_0610'), ('ranking', '0004_auto_20170611_1244'), ('ranking', '0005_auto_20170616_0212'), ('ranking', '0006_auto_20170616_0233'), ('ranking', '0007_auto_20170619_0423'), ('ranking', '0008_auto_20170619_1011'), ('ranking', '0009_auto_20170619_1032'), ('ranking', '0010_auto_20170623_0327'), ('ranking', '0011_remove_user_is_active'), ('ranking', '0012_user_is_active')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_question', models.IntegerField(default=0)),
                ('result_coding_time', models.IntegerField(default=0)),
                ('result_running_time', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('result_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('arc_user_name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.User'),
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=185, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 6, 11, 1, 34, 43, 724008, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='result_language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Others', 'Others')], max_length=15),
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result_question',
            new_name='result_problem',
        ),
        migrations.AlterField(
            model_name='result',
            name='result_problem',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='identifier',
            new_name='username',
        ),
        migrations.CreateModel(
            name='AtCoderProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=20)),
                ('task_a', models.CharField(blank=True, max_length=500, null=True)),
                ('task_b', models.CharField(blank=True, max_length=500, null=True)),
                ('task_c', models.CharField(blank=True, max_length=500, null=True)),
                ('task_d', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='result_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.AtCoderProblem'),
        ),
        migrations.CreateModel(
            name='AGCProblem',
            fields=[
                ('atcoderproblem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ranking.AtCoderProblem')),
                ('task_e', models.CharField(blank=True, max_length=500, null=True)),
                ('task_f', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('ranking.atcoderproblem',),
        ),
        migrations.AddField(
            model_name='atcoderproblem',
            name='users',
            field=models.ManyToManyField(to='ranking.User'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='arc_user_name',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='arc name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
