# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('arc_user_name', models.CharField(blank=True, max_length=15, verbose_name='arc name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('delete', models.BooleanField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('main_language', models.CharField(default='', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtCoderProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=20)),
                ('task_a', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('task_b', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('task_c', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('task_d', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('task_e', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('task_f', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_language', models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Others', 'Others')], max_length=15)),
                ('result_coding_time', models.IntegerField(default=0)),
                ('result_running_time', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('result_code', models.CharField(blank=True, max_length=500, null=True)),
                ('result_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.AtCoderProblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
