# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=185, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 6, 11, 1, 34, 43, 724008, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
