# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170611_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result_language',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_question',
            field=models.CharField(default='', max_length=30),
        ),
    ]
