# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20170611_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result_question',
            new_name='result_problem',
        ),
    ]
