# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='main_language',
            field=models.CharField(default='', max_length=15),
        ),
    ]
