# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20170611_1244'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
