# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20170616_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identifier',
            new_name='username',
        ),
    ]
