# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-19 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20170619_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atcoderproblem',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='user',
            name='answered_problem',
            field=models.ManyToManyField(to='ranking.AtCoderProblem'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_language',
            field=models.CharField(max_length=15),
        ),
    ]
