# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_auto_20170619_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answered_problem',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='delete',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_language',
            field=models.CharField(choices=[('Python', 'Python'), ('C++', 'C++'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='arc_user_name',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='arc name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='username'),
        ),
    ]
