# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20170623_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
